# Site settings
title:       Henggana
email:       henggana7@gmail.com
author:      Segi Henggana
description: "Blog of Segi Henggana"
baseurl:     ""
url:         "http://henggana.github.io"

# Disqus
disqus_shortname: "henggana"

# Google analytics
google_analytics: "UA-57998330-1"

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username: henggana
twitter_username: henggana
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    /:categories/:title
paginate:     3
sass:
  compressed: true
